import type { MesRequest, WorklogEntry } from './_types';

// ─── Request Workflow Mock Data ───────────────────────────────────────────────

export const INITIAL_REQUESTS: MesRequest[] = [
  {
    id: 'REQ-001',
    title: 'Production Line 1 — Pump Vibration & Pressure Drop',
    costCenter: 'CC-ENG-001',
    requester: 'Sarah Kim',
    technician: 'James Wilson',
    status: 'Closed',
    priority: 'High',
    machine: 'Pump Station A',
    description: 'Main circulation pump showing abnormal vibration and pressure drop. Suspected bearing wear. Needs immediate inspection and replacement if confirmed.',
    remark: 'Completed ahead of schedule. Bearing replaced and system tested.',
    createdDate: '2026-04-10',
    updatedDate: '2026-04-15',
    timeline: [
      { date: '2026-04-10', action: 'Created',    by: 'Sarah Kim' },
      { date: '2026-04-10', action: 'Submitted',  by: 'Sarah Kim' },
      { date: '2026-04-11', action: 'Approved',   by: 'Manager Chen',  note: 'Priority escalated to High' },
      { date: '2026-04-12', action: 'Started',    by: 'James Wilson' },
      { date: '2026-04-13', action: 'In Progress', by: 'James Wilson', note: 'Bearing removed, replacement parts arrived' },
      { date: '2026-04-14', action: 'Job Done',   by: 'James Wilson',  note: 'Pump reassembled and pressure tested OK' },
      { date: '2026-04-15', action: 'Closed',     by: 'Sarah Kim' },
    ],
    worklogs: [
      { id: 'WRK-001-1', date: '2026-04-12', technician: 'James Wilson', hours: 4, note: 'Initial inspection, vibration measurement, parts order' },
      { id: 'WRK-001-2', date: '2026-04-13', technician: 'James Wilson', hours: 6, note: 'Bearing removal, shaft inspection, reassembly' },
      { id: 'WRK-001-3', date: '2026-04-14', technician: 'James Wilson', hours: 2, note: 'Pressure and vibration test, handover documentation' },
    ],
  },
  {
    id: 'REQ-002',
    title: 'Line 2 Conveyor Belt Misalignment',
    costCenter: 'CC-MNT-002',
    requester: 'David Lee',
    technician: 'Alex Chen',
    status: 'Job Done',
    priority: 'Medium',
    machine: 'Conveyor Line 2',
    description: 'Belt tracking off-center causing material spillage. Idler alignment and tension adjustment required.',
    remark: 'Job completed. Awaiting requester sign-off.',
    createdDate: '2026-05-01',
    updatedDate: '2026-05-07',
    timeline: [
      { date: '2026-05-01', action: 'Created',    by: 'David Lee' },
      { date: '2026-05-02', action: 'Submitted',  by: 'David Lee' },
      { date: '2026-05-03', action: 'Approved',   by: 'Manager Chen' },
      { date: '2026-05-05', action: 'Started',    by: 'Alex Chen' },
      { date: '2026-05-06', action: 'In Progress', by: 'Alex Chen', note: 'Idler adjusted, belt tension recalculated' },
      { date: '2026-05-07', action: 'Job Done',   by: 'Alex Chen', note: 'Alignment verified, no spillage observed' },
    ],
    worklogs: [
      { id: 'WRK-002-1', date: '2026-05-05', technician: 'Alex Chen', hours: 3, note: 'Inspection and alignment planning' },
      { id: 'WRK-002-2', date: '2026-05-06', technician: 'Alex Chen', hours: 5, note: 'Idler adjustment, tension correction, run test' },
      { id: 'WRK-002-3', date: '2026-05-07', technician: 'Alex Chen', hours: 1, note: 'Final verification and report' },
    ],
  },
  {
    id: 'REQ-003',
    title: 'Electrical Panel Overheating — Building B',
    costCenter: 'CC-ENG-003',
    requester: 'Emma Rodriguez',
    technician: 'David Lee',
    status: 'In Progress',
    priority: 'Critical',
    machine: 'MDB Panel B-04',
    description: 'Main distribution board in Building B running above rated temperature (>65°C). Risk of trip or damage. Thermal imaging scan and load balancing required.',
    remark: '',
    createdDate: '2026-05-12',
    updatedDate: '2026-05-15',
    timeline: [
      { date: '2026-05-12', action: 'Created',    by: 'Emma Rodriguez' },
      { date: '2026-05-12', action: 'Submitted',  by: 'Emma Rodriguez', note: 'Critical — thermal alarm triggered' },
      { date: '2026-05-13', action: 'Approved',   by: 'Manager Chen', note: 'Immediate action authorized' },
      { date: '2026-05-14', action: 'Started',    by: 'David Lee' },
      { date: '2026-05-15', action: 'In Progress', by: 'David Lee', note: 'Thermal imaging complete, load redistribution underway' },
    ],
    worklogs: [
      { id: 'WRK-003-1', date: '2026-05-14', technician: 'David Lee', hours: 3, note: 'Thermal imaging scan, circuit load analysis' },
      { id: 'WRK-003-2', date: '2026-05-15', technician: 'David Lee', hours: 5, note: 'Load redistribution, bus bar inspection' },
    ],
  },
  {
    id: 'REQ-004',
    title: 'HVAC Filter Replacement — Server Room',
    costCenter: 'CC-FAC-001',
    requester: 'Maria Santos',
    technician: 'James Wilson',
    status: 'Started',
    priority: 'Medium',
    machine: 'AHU-SR-01',
    description: 'Quarterly filter replacement and coil cleaning for server room AHU. Airflow efficiency has dropped per monitoring data.',
    remark: '',
    createdDate: '2026-05-14',
    updatedDate: '2026-05-16',
    timeline: [
      { date: '2026-05-14', action: 'Created',   by: 'Maria Santos' },
      { date: '2026-05-14', action: 'Submitted', by: 'Maria Santos' },
      { date: '2026-05-15', action: 'Approved',  by: 'Manager Chen' },
      { date: '2026-05-16', action: 'Started',   by: 'James Wilson' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-005',
    title: 'Network Switch Firmware Upgrade',
    costCenter: 'CC-IT-001',
    requester: 'Maria Santos',
    technician: 'Emma Rodriguez',
    status: 'Approved',
    priority: 'Low',
    machine: 'Core Switch SW-01',
    description: 'Scheduled firmware upgrade for core network switch to patch CVE-2025-xxxx. Maintenance window required.',
    remark: 'Schedule during off-hours to minimize disruption.',
    createdDate: '2026-05-16',
    updatedDate: '2026-05-17',
    timeline: [
      { date: '2026-05-16', action: 'Created',   by: 'Maria Santos' },
      { date: '2026-05-16', action: 'Submitted', by: 'Maria Santos' },
      { date: '2026-05-17', action: 'Approved',  by: 'Manager Chen', note: 'Off-hours window approved' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-006',
    title: 'Forklift Battery Replacement — Warehouse A',
    costCenter: 'CC-OPS-001',
    requester: 'Sarah Kim',
    technician: '',
    status: 'Submitted',
    priority: 'High',
    machine: 'Forklift FL-003',
    description: 'Battery capacity dropped below 60%. Forklift cannot complete full shift. Replacement required before Q2 production ramp-up.',
    remark: '',
    createdDate: '2026-05-18',
    updatedDate: '2026-05-18',
    timeline: [
      { date: '2026-05-18', action: 'Created',   by: 'Sarah Kim' },
      { date: '2026-05-18', action: 'Submitted', by: 'Sarah Kim' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-007',
    title: 'Boiler Safety Valve Inspection',
    costCenter: 'CC-ENG-002',
    requester: 'David Lee',
    technician: '',
    status: 'Submitted',
    priority: 'High',
    machine: 'Boiler BLR-02',
    description: 'Annual statutory inspection of safety relief valves. Required for compliance renewal. Inspecting authority visit scheduled for June.',
    remark: '',
    createdDate: '2026-05-20',
    updatedDate: '2026-05-20',
    timeline: [
      { date: '2026-05-20', action: 'Created',   by: 'David Lee' },
      { date: '2026-05-20', action: 'Submitted', by: 'David Lee' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-008',
    title: 'Compressor Oil Sampling — Line 4',
    costCenter: 'CC-ENG-004',
    requester: 'Emma Rodriguez',
    technician: '',
    status: 'Draft',
    priority: 'Low',
    machine: 'Air Compressor AC-04',
    description: 'Routine oil sampling and analysis to assess compressor wear. Last sample taken 6 months ago.',
    remark: '',
    createdDate: '2026-05-22',
    updatedDate: '2026-05-22',
    timeline: [
      { date: '2026-05-22', action: 'Created', by: 'Emma Rodriguez' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-009',
    title: 'Fire Suppression System Annual Test',
    costCenter: 'CC-FAC-002',
    requester: 'Sarah Kim',
    technician: '',
    status: 'Draft',
    priority: 'Critical',
    machine: 'Fire System FS-ALL',
    description: 'Annual test of all fire suppression zones, detectors, and control panels. Mandatory per regulatory requirement.',
    remark: '',
    createdDate: '2026-05-23',
    updatedDate: '2026-05-23',
    timeline: [
      { date: '2026-05-23', action: 'Created', by: 'Sarah Kim' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-010',
    title: 'Cooling Tower Water Treatment',
    costCenter: 'CC-MNT-003',
    requester: 'David Lee',
    technician: 'Alex Chen',
    status: 'Rejected',
    priority: 'Medium',
    machine: 'Cooling Tower CT-01',
    description: 'Request for water treatment chemical dosing and blowdown cycle adjustment.',
    remark: 'Rejected: Incomplete water analysis report. Resubmit with lab results attached.',
    createdDate: '2026-05-10',
    updatedDate: '2026-05-11',
    timeline: [
      { date: '2026-05-10', action: 'Created',   by: 'David Lee' },
      { date: '2026-05-10', action: 'Submitted', by: 'David Lee' },
      { date: '2026-05-11', action: 'Rejected',  by: 'Manager Chen', note: 'Missing water analysis report — resubmit with lab results' },
    ],
    worklogs: [],
  },
  {
    id: 'REQ-011',
    title: 'Weighing Scale Calibration — Warehouse B',
    costCenter: 'CC-OPS-002',
    requester: 'Maria Santos',
    technician: 'James Wilson',
    status: 'Closed',
    priority: 'Low',
    machine: 'Platform Scale WB-02',
    description: 'Quarterly calibration of warehouse platform scale. Due per calibration schedule.',
    remark: 'Calibrated. Certificate issued.',
    createdDate: '2026-04-20',
    updatedDate: '2026-04-24',
    timeline: [
      { date: '2026-04-20', action: 'Created',    by: 'Maria Santos' },
      { date: '2026-04-20', action: 'Submitted',  by: 'Maria Santos' },
      { date: '2026-04-21', action: 'Approved',   by: 'Manager Chen' },
      { date: '2026-04-22', action: 'Started',    by: 'James Wilson' },
      { date: '2026-04-23', action: 'In Progress', by: 'James Wilson', note: 'Calibration weights applied, adjustments made' },
      { date: '2026-04-23', action: 'Job Done',   by: 'James Wilson', note: 'Certificate of calibration issued' },
      { date: '2026-04-24', action: 'Closed',     by: 'Maria Santos' },
    ],
    worklogs: [
      { id: 'WRK-011-1', date: '2026-04-22', technician: 'James Wilson', hours: 2, note: 'Pre-calibration inspection and setup' },
      { id: 'WRK-011-2', date: '2026-04-23', technician: 'James Wilson', hours: 3, note: 'Calibration procedure and certificate prep' },
    ],
  },
  {
    id: 'REQ-012',
    title: 'CNC Machine Spindle Noise Investigation',
    costCenter: 'CC-ENG-005',
    requester: 'Alex Chen',
    technician: 'David Lee',
    status: 'In Progress',
    priority: 'High',
    machine: 'CNC-05 Spindle',
    description: 'Unusual high-frequency noise from CNC spindle at high RPM. Suspected bearing or imbalance issue. Production has been rescheduled pending repair.',
    remark: '',
    createdDate: '2026-05-19',
    updatedDate: '2026-05-22',
    timeline: [
      { date: '2026-05-19', action: 'Created',    by: 'Alex Chen' },
      { date: '2026-05-19', action: 'Submitted',  by: 'Alex Chen' },
      { date: '2026-05-20', action: 'Approved',   by: 'Manager Chen', note: 'Production impact — priority confirmed' },
      { date: '2026-05-21', action: 'Started',    by: 'David Lee' },
      { date: '2026-05-22', action: 'In Progress', by: 'David Lee', note: 'Spindle disassembled, bearing wear confirmed' },
    ],
    worklogs: [
      { id: 'WRK-012-1', date: '2026-05-21', technician: 'David Lee', hours: 4, note: 'Noise diagnosis, spindle disassembly, wear measurement' },
      { id: 'WRK-012-2', date: '2026-05-22', technician: 'David Lee', hours: 3, note: 'Bearing removal, parts order placed' },
    ],
  },
];

// ─── Timesheet / Worklog Mock Data ────────────────────────────────────────────

export const EMPLOYEES: { name: string; dept: string }[] = [
  { name: 'Alex Chen',      dept: 'Engineering' },
  { name: 'Maria Santos',   dept: 'IT Support'  },
  { name: 'David Lee',      dept: 'Engineering' },
  { name: 'Sarah Kim',      dept: 'Operations'  },
  { name: 'James Wilson',   dept: 'Maintenance' },
  { name: 'Emma Rodriguez', dept: 'IT Support'  },
];

export const DEPARTMENTS = ['Engineering', 'IT Support', 'Operations', 'Maintenance'];

export const WORK_CENTERS = ['Facility A', 'Facility B', 'Control Room', 'Server Room'];

export const TASKS = [
  'Preventive Maintenance',
  'Corrective Repair',
  'System Inspection',
  'Equipment Calibration',
  'Software Deployment',
  'Network Setup',
];

export const INITIAL_WORKLOGS: WorklogEntry[] = [
  { id: 'WL-001', workDate: '2026-05-01', employeeName: 'Alex Chen',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '18:30', workHours: 11.5, otHours: 2.5, workCenter: 'Facility A',  task: 'Preventive Maintenance', status: 'Approved',  remark: 'Monthly PM — production line 1'    },
  { id: 'WL-002', workDate: '2026-05-02', employeeName: 'Maria Santos',   department: 'IT Support',  shift: 'Morning',   startTime: '08:00', endTime: '17:00', workHours: 9,    otHours: 1,   workCenter: 'Server Room',   task: 'Software Deployment',    status: 'Approved',  remark: 'OS patch deployment'               },
  { id: 'WL-003', workDate: '2026-05-05', employeeName: 'David Lee',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '20:00', workHours: 13,   otHours: 4,   workCenter: 'Facility B',   task: 'Corrective Repair',      status: 'Approved',  remark: 'Emergency pump repair'             },
  { id: 'WL-004', workDate: '2026-05-06', employeeName: 'Sarah Kim',      department: 'Operations',  shift: 'Afternoon', startTime: '13:00', endTime: '22:00', workHours: 9,    otHours: 0,   workCenter: 'Control Room', task: 'System Inspection',      status: 'Approved',  remark: ''                                  },
  { id: 'WL-005', workDate: '2026-05-07', employeeName: 'James Wilson',   department: 'Maintenance', shift: 'Morning',   startTime: '07:30', endTime: '19:00', workHours: 11.5, otHours: 3,   workCenter: 'Facility A',  task: 'Equipment Calibration',  status: 'Submitted', remark: 'Annual calibration cycle'          },
  { id: 'WL-006', workDate: '2026-05-08', employeeName: 'Emma Rodriguez', department: 'IT Support',  shift: 'Morning',   startTime: '09:00', endTime: '18:00', workHours: 9,    otHours: 2,   workCenter: 'Server Room',  task: 'Network Setup',          status: 'Submitted', remark: 'Network restructure phase 2'       },
  { id: 'WL-007', workDate: '2026-05-12', employeeName: 'Alex Chen',      department: 'Engineering', shift: 'Night',     startTime: '22:00', endTime: '07:00', workHours: 9,    otHours: 0,   workCenter: 'Facility B',   task: 'Preventive Maintenance', status: 'Submitted', remark: 'Night shift scheduled PM'          },
  { id: 'WL-008', workDate: '2026-05-13', employeeName: 'David Lee',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '16:00', workHours: 9,    otHours: 0,   workCenter: 'Facility A',  task: 'System Inspection',      status: 'Draft',     remark: ''                                  },
  { id: 'WL-009', workDate: '2026-05-14', employeeName: 'Maria Santos',   department: 'IT Support',  shift: 'Morning',   startTime: '08:00', endTime: '17:30', workHours: 9.5,  otHours: 1.5, workCenter: 'Server Room',  task: 'Software Deployment',    status: 'Draft',     remark: 'Staging environment'               },
  { id: 'WL-010', workDate: '2026-05-15', employeeName: 'Sarah Kim',      department: 'Operations',  shift: 'Morning',   startTime: '07:00', endTime: '16:00', workHours: 9,    otHours: 0,   workCenter: 'Control Room', task: 'System Inspection',      status: 'Rejected',  remark: 'Incomplete documentation'          },
  { id: 'WL-011', workDate: '2026-04-01', employeeName: 'James Wilson',   department: 'Maintenance', shift: 'Morning',   startTime: '07:00', endTime: '19:00', workHours: 12,   otHours: 3,   workCenter: 'Facility A',  task: 'Preventive Maintenance', status: 'Approved',  remark: 'Q2 scheduled PM'                   },
  { id: 'WL-012', workDate: '2026-04-03', employeeName: 'Alex Chen',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '18:00', workHours: 11,   otHours: 2,   workCenter: 'Facility B',   task: 'Equipment Calibration',  status: 'Approved',  remark: ''                                  },
  { id: 'WL-013', workDate: '2026-04-07', employeeName: 'Emma Rodriguez', department: 'IT Support',  shift: 'Morning',   startTime: '08:00', endTime: '20:00', workHours: 12,   otHours: 4,   workCenter: 'Server Room',  task: 'Network Setup',          status: 'Approved',  remark: 'Critical network upgrade'          },
  { id: 'WL-014', workDate: '2026-04-10', employeeName: 'David Lee',      department: 'Engineering', shift: 'Afternoon', startTime: '13:00', endTime: '22:00', workHours: 9,    otHours: 0,   workCenter: 'Facility A',  task: 'Corrective Repair',      status: 'Approved',  remark: ''                                  },
  { id: 'WL-015', workDate: '2026-04-14', employeeName: 'Sarah Kim',      department: 'Operations',  shift: 'Morning',   startTime: '07:00', endTime: '17:30', workHours: 10.5, otHours: 1.5, workCenter: 'Control Room', task: 'System Inspection',      status: 'Approved',  remark: ''                                  },
  { id: 'WL-016', workDate: '2026-04-17', employeeName: 'Maria Santos',   department: 'IT Support',  shift: 'Morning',   startTime: '08:00', endTime: '19:00', workHours: 11,   otHours: 3,   workCenter: 'Server Room',  task: 'Software Deployment',    status: 'Approved',  remark: 'Major version upgrade'             },
  { id: 'WL-017', workDate: '2026-04-21', employeeName: 'Alex Chen',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '16:00', workHours: 9,    otHours: 0,   workCenter: 'Facility A',  task: 'Preventive Maintenance', status: 'Approved',  remark: ''                                  },
  { id: 'WL-018', workDate: '2026-04-24', employeeName: 'James Wilson',   department: 'Maintenance', shift: 'Night',     startTime: '22:00', endTime: '07:00', workHours: 9,    otHours: 0,   workCenter: 'Facility B',   task: 'Equipment Calibration',  status: 'Approved',  remark: 'Night shift calibration'           },
  { id: 'WL-019', workDate: '2026-04-28', employeeName: 'Emma Rodriguez', department: 'IT Support',  shift: 'Morning',   startTime: '09:00', endTime: '20:00', workHours: 11,   otHours: 4,   workCenter: 'Server Room',  task: 'Network Setup',          status: 'Approved',  remark: 'DR setup completion'               },
  { id: 'WL-020', workDate: '2026-04-30', employeeName: 'David Lee',      department: 'Engineering', shift: 'Morning',   startTime: '07:00', endTime: '18:00', workHours: 11,   otHours: 2,   workCenter: 'Facility B',   task: 'Corrective Repair',      status: 'Approved',  remark: 'End-of-month repair log'           },
];
